### ISSUE TITLE
Font needs to be scaled

### ISSUE THREAD

**Issue by aaronbell** [mt-funa/Tsukimi-Rounded#1]
The [Google vertical metrics specification](https://github.com/googlefonts/gf-docs/tree/master/Spec#cjk-vertical-metrics) states that the winDescent value must be -288, and that no glyph can be deeper than that value in order to avoid risk of clipping. In Tsukimi Rounded, there are several glyphs that exceed that value:
- J
- g
- y
- yacute
- ydieresis
- exclamdown
- questiondown
- micro

The lowest, exclamdown, is at -311. As such, I suggest scaling the font by 12% (or at 88% in the Glyphs transformations pane) to ensure that all glyphs remain within the BBox.

**Comment by mt-funa** [comment]
I corrected the glyph that was pointed out.

**Comment by aaronbell** [comment]
Great! Thanks :)
