### ISSUE TITLE
Many glyphs missing extremes

### ISSUE THREAD

**Issue by aaronbell** [mt-funa/Tsukimi-Rounded#2]
Given that this font will be autohinted, we need to have points at extremes, particularly in the y-direction, to ensure the best quality rendering as a TTF. As such, please correct the glyphs that are missing points at extremes:

0041 A A
00C1 Á Aacute
00C2 Â Acircumflex
00C4 Ä Adieresis
00C0 À Agrave
00C5 Å Aring
00C3 Ã Atilde
00C6 Æ AE
0042 B B
0043 C C
00C7 Ç Ccedilla
0044 D D
00D0 Ð Eth
0045 E E
00C9 É Eacute
00CA Ê Ecircumflex
00CB Ë Edieresis
00C8 È Egrave
0046 F F
0047 G G
0048 H H
0049 I I
00CD Í Iacute
00CE Î Icircumflex
00CF Ï Idieresis
00CC Ì Igrave
004A J J
004B K K
004C L L
004D M M
004E N N
00D1 Ñ Ntilde
004F O O
00D3 Ó Oacute
00D4 Ô Ocircumflex
00D6 Ö Odieresis
00D2 Ò Ograve
00D8 Ø Oslash
00D5 Õ Otilde
0152 Œ OE
0050 P P
00DE Þ Thorn
0051 Q Q
0052 R R
0053 S S
0054 T T
0055 U U
00DA Ú Uacute
00DB Û Ucircumflex
00DC Ü Udieresis
00D9 Ù Ugrave
0056 V V
0057 W W
1E82 Ẃ Wacute
0174 Ŵ Wcircumflex
1E84 Ẅ Wdieresis
1E80 Ẁ Wgrave
0058 X X
0059 Y Y
00DD Ý Yacute
005A Z Z
None  W.ss01
0061 a a
00E1 á aacute
00E2 â acircumflex
00E4 ä adieresis
00E0 à agrave
00E5 å aring
00E3 ã atilde
00E6 æ ae
0062 b b
0063 c c
00E7 ç ccedilla
0064 d d
00F0 ð eth
0065 e e
00E9 é eacute
00EA ê ecircumflex
00EB ë edieresis
00E8 è egrave
0066 f f
0067 g g
0068 h h
0069 i i
0131 ı idotless
00ED í iacute
00EE î icircumflex
00EF ï idieresis
00EC ì igrave
006A j j
006B k k
006C l l
006D m m
006E n n
00F1 ñ ntilde
006F o o
00F3 ó oacute
00F4 ô ocircumflex
00F6 ö odieresis
00F2 ò ograve
00F8 ø oslash
00F5 õ otilde
0153 œ oe
0070 p p
00FE þ thorn
0071 q q
0072 r r
0073 s s
00DF ß germandbls
0074 t t
0075 u u
00FA ú uacute
00FB û ucircumflex
00FC ü udieresis
00F9 ù ugrave
0076 v v
0077 w w
1E83 ẃ wacute
0175 ŵ wcircumflex
1E85 ẅ wdieresis
1E81 ẁ wgrave
0078 x x
0079 y y
00FD ý yacute
00FF ÿ ydieresis
007A z z
None  w.ss01
None  f_i
None  f_l
00AA ª ordfeminine
00BA º ordmasculine
3042 あ a-hira
3041 ぁ asmall-hira
3044 い i-hira
3043 ぃ ismall-hira
3046 う u-hira
3045 ぅ usmall-hira
3048 え e-hira
3047 ぇ esmall-hira
304A お o-hira
3049 ぉ osmall-hira
304B か ka-hira
304C が ga-hira
304D き ki-hira
304E ぎ gi-hira
304F く ku-hira
3050 ぐ gu-hira
3051 け ke-hira
3052 げ ge-hira
3053 こ ko-hira
3054 ご go-hira
3055 さ sa-hira
3056 ざ za-hira
3057 し si-hira
3058 じ zi-hira
3059 す su-hira
305A ず zu-hira
305B せ se-hira
305C ぜ ze-hira
305D そ so-hira
305E ぞ zo-hira
305F た ta-hira
3060 だ da-hira
3061 ち ti-hira
3062 ぢ di-hira
3064 つ tu-hira
3063 っ tusmall-hira
3065 づ du-hira
3066 て te-hira
3067 で de-hira
3068 と to-hira
3069 ど do-hira
306A な na-hira
306B に ni-hira
306C ぬ nu-hira
306D ね ne-hira
306E の no-hira
306F は ha-hira
3070 ば ba-hira
3071 ぱ pa-hira
3072 ひ hi-hira
3073 び bi-hira
3074 ぴ pi-hira
3075 ふ hu-hira
3076 ぶ bu-hira
3077 ぷ pu-hira
3078 へ he-hira
3079 べ be-hira
307A ぺ pe-hira
307B ほ ho-hira
307C ぼ bo-hira
307D ぽ po-hira
307E ま ma-hira
307F み mi-hira
3080 む mu-hira
3081 め me-hira
3082 も mo-hira
3084 や ya-hira
3083 ゃ yasmall-hira
3086 ゆ yu-hira
3085 ゅ yusmall-hira
3088 よ yo-hira
3087 ょ yosmall-hira
3089 ら ra-hira
308A り ri-hira
308B る ru-hira
308C れ re-hira
308D ろ ro-hira
308F わ wa-hira
308E ゎ wasmall-hira
3090 ゐ wi-hira
3091 ゑ we-hira
3092 を wo-hira
3093 ん n-hira
3094 ゔ vu-hira
30A2 ア a-kata
30A1 ァ asmall-kata
30A4 イ i-kata
30A3 ィ ismall-kata
30A6 ウ u-kata
30A5 ゥ usmall-kata
30A8 エ e-kata
30A7 ェ esmall-kata
30AA オ o-kata
30A9 ォ osmall-kata
30AB カ ka-kata
30F5 ヵ kasmall-kata
30AC ガ ga-kata
30AD キ ki-kata
30AE ギ gi-kata
30AF ク ku-kata
30B0 グ gu-kata
30B1 ケ ke-kata
30F6 ヶ kesmall-kata
30B2 ゲ ge-kata
30B3 コ ko-kata
30B4 ゴ go-kata
30B5 サ sa-kata
30B6 ザ za-kata
30B7 シ si-kata
30B8 ジ zi-kata
30B9 ス su-kata
30BA ズ zu-kata
30BB セ se-kata
30BC ゼ ze-kata
30BD ソ so-kata
30BE ゾ zo-kata
30BF タ ta-kata
30C0 ダ da-kata
30C1 チ ti-kata
30C2 ヂ di-kata
30C4 ツ tu-kata
30C3 ッ tusmall-kata
30C5 ヅ du-kata
30C6 テ te-kata
30C7 デ de-kata
30C8 ト to-kata
30C9 ド do-kata
30CA ナ na-kata
30CB ニ ni-kata
30CC ヌ nu-kata
30CD ネ ne-kata
30CE ノ no-kata
30CF ハ ha-kata
30D0 バ ba-kata
30D1 パ pa-kata
30D2 ヒ hi-kata
30D3 ビ bi-kata
30D4 ピ pi-kata
30D5 フ hu-kata
30D6 ブ bu-kata
30D7 プ pu-kata
30D8 ヘ he-kata
30D9 ベ be-kata
30DA ペ pe-kata
30DB ホ ho-kata
30DC ボ bo-kata
30DD ポ po-kata
30DE マ ma-kata
30DF ミ mi-kata
30E0 ム mu-kata
30E1 メ me-kata
30E2 モ mo-kata
30E4 ヤ ya-kata
30E3 ャ yasmall-kata
30E6 ユ yu-kata
30E5 ュ yusmall-kata
30E8 ヨ yo-kata
30E7 ョ yosmall-kata
30E9 ラ ra-kata
30EA リ ri-kata
30EB ル ru-kata
30EC レ re-kata
30ED ロ ro-kata
30EF ワ wa-kata
30EE ヮ wasmall-kata
30F7 ヷ va-kata
30F0 ヰ wi-kata
30F8 ヸ vi-kata
30F1 ヱ we-kata
30F9 ヹ ve-kata
30F2 ヲ wo-kata
30FA ヺ vo-kata
30F3 ン n-kata
30F4 ヴ vu-kata
None  a-hira.ss01
None  ka-hira.ss01
None  ga-hira.ss01
None  si-hira.ss01
None  zi-hira.ss01
None  to-hira.ss01
None  do-hira.ss01
None  ne-hira.ss01
None  ha-hira.ss01
None  ba-hira.ss01
None  pa-hira.ss01
None  yu-hira.ss01
None  yo-hira.ss01
None  wo-hira.ss01
None  asmall-hira.vert
None  ismall-hira.vert
None  usmall-hira.vert
None  esmall-hira.vert
None  osmall-hira.vert
None  tusmall-hira.vert
None  yasmall-hira.vert
None  yusmall-hira.vert
None  yosmall-hira.vert
None  wasmall-hira.vert
None  asmall-kata.vert
None  ismall-kata.vert
None  usmall-kata.vert
None  esmall-kata.vert
None  osmall-kata.vert
None  kasmall-kata.vert
None  kesmall-kata.vert
None  tusmall-kata.vert
None  yasmall-kata.vert
None  yusmall-kata.vert
None  yosmall-kata.vert
FF10 ０ zero.full
FF11 １ one.full
FF12 ２ two.full
FF13 ３ three.full
FF14 ４ four.full
FF15 ５ five.full
FF16 ６ six.full
FF17 ７ seven.full
FF18 ８ eight.full
FF19 ９ nine.full
0030 0 zero
0031 1 one
0032 2 two
0033 3 three
0034 4 four
0035 5 five
0036 6 six
0037 7 seven
0038 8 eight
0039 9 nine
None  zero.dnom
None  one.dnom
None  two.dnom
None  three.dnom
None  four.dnom
None  zero.numr
None  one.numr
None  two.numr
None  three.numr
None  four.numr
2070 ⁰ zerosuperior
00B9 ¹ onesuperior
00B2 ² twosuperior
00B3 ³ threesuperior
2074 ⁴ foursuperior
2044 ⁄ fraction
00BD ½ onehalf
00BC ¼ onequarter
00BE ¾ threequarters
002E . period
002C , comma
003A : colon
003B ; semicolon
2026 … ellipsis
0021 ! exclam
00A1 ¡ exclamdown
003F ? question
00BF ¿ questiondown
00B7 · periodcentered
2022 • bullet
002A * asterisk
0023 # numbersign
002F / slash
005C \ backslash
FF01 ！ exclam.full
FF1F ？ question.full
0028 ( parenleft
0029 ) parenright
007B { braceleft
007D } braceright
005B [ bracketleft
005D ] bracketright
3008 〈 anglebracketleft
3009 〉 anglebracketright
3010 【 blacklenticularbracketleft
3011 】 blacklenticularbracketright
300C 「 cornerbracketleft
300D 」 cornerbracketright
300A 《 dblanglebracketleft
300B 》 dblanglebracketright
3014 〔 tortoiseshellbracketleft
3015 〕 tortoiseshellbracketright
300E 『 whitecornerbracketleft
300F 』 whitecornerbracketright
FE3F ︿ anglebracketleft.vert
FE40 ﹀ anglebracketright.vert
FE3B ︻ blacklenticularbracketleft.vert
FE3C ︼ blacklenticularbracketright.vert
FF3B ［ bracketleft.full
FE47 ﹇ bracketleft.full.vert
FF3D ］ bracketright.full
FE48 ﹈ bracketright.full.vert
FE41 ﹁ cornerbracketleft.vert
FE42 ﹂ cornerbracketright.vert
FE3D ︽ dblanglebracketleft.vert
FE3E ︾ dblanglebracketright.vert
FF08 （ parenleft.full
FF09 ） parenright.full
FE39 ︹ tortoiseshellbracketleft.vert
FE3A ︺ tortoiseshellbracketright.vert
FE35 ︵ parenleft.full.vert
FE36 ︶ parenright.full.vert
FE43 ﹃ whitecornerbracketleft.vert
FE44 ﹄ whitecornerbracketright.vert
002D - hyphen
00AD ­ softhyphen
2013 – endash
2014 — emdash
005F _ underscore
201A ‚ quotesinglbase
201E „ quotedblbase
201C “ quotedblleft
201D ” quotedblright
2018 ‘ quoteleft
2019 ’ quoteright
00AB « guillemetleft
00BB » guillemetright
2039 ‹ guilsinglleft
203A › guilsinglright
0022 " quotedbl
0027 ' quotesingle
30FB ・ dot-kata
3001 、 comma-han
FE11 ︑ comma-han.vert
3002 。 period-han
FE12 ︒ period-han.vert
3000 　space-han
0020   space
00A0  nbspace
None  space.full
000D 
CR
None  .notdef
00A2 ¢ cent
00A4 ¤ currency
0024 $ dollar
20AC € euro
00A3 £ sterling
00A5 ¥ yen
2215 ∕ divisionslash
002B + plus
2212 − minus
00D7 × multiply
00F7 ÷ divide
003D = equal
003E > greater
003C < less
2265 ≥ greaterequal
2264 ≤ lessequal
00B1 ± plusminus
007E ~ asciitilde
00AC ¬ logicalnot
005E ^ asciicircum
00B5 µ micro
0025 % percent
2030 ‰ perthousand
FF5E ～ asciitilde.full
None  asciitilde.full.vert
2191 ↑ upArrow
2193 ↓ downArrow
0040 @ at
0026 & ampersand
00B6 ¶ paragraph
00A7 § section
00A9 © copyright
00AE ® registered
2122 ™ trademark
00B0 ° degree
2032 ′ minute
2033 ″ second
007C | bar
00A6 ¦ brokenbar
2103 ℃ centigrade
FFFD � replacementCharacter
02BC ʼ apostrophemod
02BB ʻ commaturnedmod
0308 ̈ dieresiscomb
0300 ̀ gravecomb
0301 ́ acutecomb
0302 ̂ circumflexcomb
030A ̊ ringcomb
0303 ̃ tildecomb
0304 ̄ macroncomb
0327 ̧ cedillacomb
00A8 ¨ dieresis
0060 ` grave
00B4 ´ acute
02C6 ˆ circumflex
02DA ˚ ring
02DC ˜ tilde
00AF ¯ macron
00B8 ¸ cedilla
309D ゝ iteration-hira
309E ゞ voicediteration-hira
30FC ー prolonged-kana
30FD ヽ iteration-kata
30FE ヾ voicediteration-kata
None  prolonged-kana.vert
3099 ゙ voicedcomb-kana
309A ゚ semivoicedcomb-kana
0000  NULL
None  _cap.top
None  nh_curve
None  bp_curve

I suggest using the Glyphs plugin "Red Arrows" to locate and point out these errors.

**Comment by mt-funa** [comment]
I add points at extremes.

**Comment by aaronbell** [comment]
Thanks!
