### ISSUE TITLE
Register Vendor ID

### ISSUE THREAD

**Issue by aaronbell** [mt-funa/Tsukimi-Rounded#3]
It appears that you have not [registered a vendor ID](https://docs.microsoft.com/en-us/typography/vendors/) with Microsoft. Please [do so here](https://docs.microsoft.com/en-us/typography/vendors/register).

**Comment by mt-funa** [comment]
Thank you for your advice.
I registered following information.

• Vendor ID (Required)
FUNA

• Foundry Name (Required)
Mt. Funa Design Office

• E-mail Address
takashi@mt-funa.com

• Website
http://mt-funa.com
